version: "3.8"

services:
  db:
    container_name: arc-mysql-test
    image: mysql
    environment:
      MYSQL_DATABASE: api_rest_crud_test
      MYSQL_USER: amtineztest
      MYSQL_PASSWORD: apirestcrudtest
      MYSQL_ROOT_PASSWORD: rootapirestcrudtest
      MYSQL_TCP_PORT: 3308
    expose:
      - 3308
    ports:
      - 3308:3308
    healthcheck:
      interval: 3s
      retries: 2000
      test: /usr/bin/mysql --user=root --password=rootapirestcrud --execute "SHOW DATABASES;"
      timeout: 3s
    volumes:
      - ../../docker-data/mysql-test:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql