version: "3.8"

services:
  db:
    container_name: arc-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: api_rest_crud
      MYSQL_USER: amtinez
      MYSQL_PASSWORD: apirestcrud
      MYSQL_ROOT_PASSWORD: rootapirestcrud
      MYSQL_TCP_PORT: 3307
    expose:
      - 3307
    ports:
      - 3307:3307
    healthcheck:
      interval: 3s
      retries: 2000
      test: /usr/bin/mysql --user=root --password=rootapirestcrud --execute "SHOW DATABASES;"
      timeout: 3s
    volumes:
      - ../../docker-data/mysql:/var/lib/mysql
      - ../bbdd/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-test:
    container_name: arc-mysql-test
    image: mysql
    environment:
      MYSQL_DATABASE: api_rest_crud_test
      MYSQL_USER: amtineztest
      MYSQL_PASSWORD: apirestcrudtest
      MYSQL_ROOT_PASSWORD: rootapirestcrudtest
      MYSQL_TCP_PORT: 3308
    expose:
      - 3308
    ports:
      - 3308:3308
    healthcheck:
      interval: 3s
      retries: 2000
      test: /usr/bin/mysql --user=root --password=rootapirestcrud --execute "SHOW DATABASES;"
      timeout: 3s
    volumes:
      - ../../docker-data/mysql-test:/var/lib/mysql
      - ../bbdd/init-test.sql:/docker-entrypoint-initdb.d/init.sql

  sonarqube:
    container_name: arc-sonarqube
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    environment:
      - sonar.login=admin
      - sonar.password=nimda
    volumes:
      - ../../docker-data/sonarqube/data:/opt/sonarqube/data
      - ../../docker-data/sonarqube/extensions:/opt/sonarqube/extensions