version: "3.8"

services:
  db:
    container_name: arc-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: api_rest_crud
      MYSQL_USER: amtinez
      MYSQL_PASSWORD: apirestcrud
      MYSQL_ROOT_PASSWORD: rootapirestcrud
      MYSQL_TCP_PORT: 3307
    expose:
      - 3307
    ports:
      - 3307:3307
    healthcheck:
      interval: 3s
      retries: 2000
      test: /usr/bin/mysql --user=root --password=rootapirestcrud --execute "SHOW DATABASES;"
      timeout: 3s
    volumes:
    - /Users/almartinez/personal/api-rest-crud/docker-data/mysql:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql